CREATE SCHEMA cdp;

USE cdp;

CREATE TABLE enumeration_type (
  ENUM_TYPE_ID varchar(40),
  DESCRIPTION varchar(255),
  LAST_UPDATED_STAMP datetime(3),
  PRIMARY KEY (ENUM_TYPE_ID)
);

CREATE TABLE enumeration (
  ENUM_ID varchar(40),
  ENUM_TYPE_ID varchar(40),
  PARENT_ENUM_ID varchar(40),
  ENUM_CODE varchar(255),
  SEQUENCE_NUM decimal(20,0),
  DESCRIPTION varchar(255),
  OPTION_VALUE varchar(255),
  OPTION_INDICATOR char(1),
  RELATED_ENUM_ID varchar(40),
  RELATED_ENUM_TYPE_ID varchar(40),
  STATUS_FLOW_ID varchar(40),
  LAST_UPDATED_STAMP datetime(3),
  PRIMARY KEY (ENUM_ID),
  FOREIGN KEY (ENUM_TYPE_ID) REFERENCES enumeration_type(ENUM_TYPE_ID)
);

CREATE TABLE geo (
  GEO_ID varchar(40),
  GEO_TYPE_ENUM_ID varchar(40),
  GEO_NAME varchar(255),
  GEO_NAME_LOCAL varchar(255),
  GEO_CODE_ALPHA2 varchar(63),
  GEO_CODE_ALPHA3 varchar(63),
  GEO_CODE_NUMERIC varchar(63),
  WELL_KNOWN_TEXT longtext,
  LAST_UPDATED_STAMP datetime(3),
  PRIMARY KEY (GEO_ID),
  FOREIGN KEY (GEO_TYPE_ENUM_ID) REFERENCES enumeration(ENUM_ID)
);

CREATE TABLE uom (
  UOM_ID varchar(40),
  UOM_TYPE_ENUM_ID varchar(40),
  ABBREVIATION varchar(63),
  DESCRIPTION varchar(255),
  FRACTION_DIGITS decimal(20,0),
  SYMBOL varchar(63),
  LAST_UPDATED_STAMP datetime(3),
  PRIMARY KEY (UOM_ID),
  FOREIGN KEY (UOM_TYPE_ENUM_ID) REFERENCES enumeration(ENUM_ID)
);

CREATE TABLE system_message_remote (
  SYSTEM_MESSAGE_REMOTE_ID varchar(40),
  DESCRIPTION varchar(255),
  SEND_URL varchar(255),
  RECEIVE_URL varchar(255),
  REMOTE_CHARSET varchar(63),
  REMOTE_ATTRIBUTES char(1),
  SEND_SERVICE_NAME varchar(255),
  USERNAME varchar(255),
  PASSWORD varchar(255),
  PUBLIC_KEY varchar(4095),
  PRIVATE_KEY varchar(4095),
  REMOTE_PUBLIC_KEY varchar(4095),
  SHARED_SECRET varchar(255),
  SEND_SHARED_SECRET varchar(255),
  AUTH_HEADER_NAME varchar(255),
  MESSAGE_AUTH_ENUM_ID varchar(40),
  SEND_AUTH_ENUM_ID varchar(40),
  SYSTEM_MESSAGE_TYPE_ID varchar(40),
  INTERNAL_ID varchar(63),
  INTERNAL_ID_TYPE varchar(63),
  INTERNAL_APP_CODE varchar(255),
  REMOTE_ID varchar(63),
  REMOTE_ID_TYPE varchar(63),
  REMOTE_APP_CODE varchar(255),
  ACK_REQUESTED varchar(63),
  USAGE_CODE varchar(63),
  SEGMENT_TERMINATOR char(1),
  ELEMENT_SEPARATOR char(1),
  COMPONENT_DELIMITER char(1),
  ESCAPE_CHARACTER char(1),
  PRE_AUTH_MESSAGE_REMOTE_ID varchar(40),
  LAST_UPDATED_STAMP datetime(3),
  PRIMARY KEY (SYSTEM_MESSAGE_REMOTE_ID),
  FOREIGN KEY (MESSAGE_AUTH_ENUM_ID) REFERENCES enumeration(ENUM_ID),
  FOREIGN KEY (SEND_AUTH_ENUM_ID) REFERENCES enumeration(ENUM_ID),
  FOREIGN KEY (PRE_AUTH_MESSAGE_REMOTE_ID) REFERENCES system_message_remote(SYSTEM_MESSAGE_REMOTE_ID)
);

CREATE TABLE product_store (
  PRODUCT_STORE_ID varchar(40),
  STORE_NAME varchar(255),
  ORGANIZATION_PARTY_ID varchar(40),
  RESERVATION_ORDER_ENUM_ID varchar(40),
  RESERVATION_AUTO_ENUM_ID varchar(40),
  REQUIRE_INVENTORY char(1),
  DEFAULT_DISABLE_PROMOTIONS char(1),
  DEFAULT_DISABLE_SHIPPING_CALC char(1),
  DEFAULT_DISABLE_TAX_CALC char(1),
  RETURN_POSTAL_CONTACT_MECH_ID varchar(40),
  MARKUP_ORDER_SHIP_LABELS char(1),
  MARKUP_SHIPMENT_SHIP_LABELS char(1),
  SHIPMENT_ANY_CARRIER_METHOD char(1),
  INSURANCE_PACKAGE_THRESHOLD decimal(24,4),
  AUTO_APPROVE_DELAY decimal(20,0),
  STORE_DOMAIN varchar(63),
  PROFILE_URL_PATH varchar(255),
  DEFAULT_LOCALE varchar(63),
  DEFAULT_CURRENCY_UOM_ID varchar(40),
  DEFAULT_SALES_CHANNEL_ENUM_ID varchar(40),
  REQUIRE_CUSTOMER_ROLE char(1),
  SYSTEM_MESSAGE_REMOTE_ID varchar(40),
  LAST_UPDATED_STAMP datetime(3),
  PRIMARY KEY (PRODUCT_STORE_ID),
  FOREIGN KEY (ORGANIZATION_PARTY_ID) REFERENCES party(PARTY_ID),
  FOREIGN KEY (RESERVATION_ORDER_ENUM_ID) REFERENCES enumeration(ENUM_ID),
  FOREIGN KEY (RESERVATION_AUTO_ENUM_ID) REFERENCES enumeration(ENUM_ID),
  FOREIGN KEY (RETURN_POSTAL_CONTACT_MECH_ID) REFERENCES postal_address(CONTACT_MECH_ID),
  FOREIGN KEY (DEFAULT_CURRENCY_UOM_ID) REFERENCES uom(UOM_ID),
  FOREIGN KEY (DEFAULT_SALES_CHANNEL_ENUM_ID) REFERENCES enumeration(ENUM_ID),
  FOREIGN KEY (SYSTEM_MESSAGE_REMOTE_ID) REFERENCES system_message_remote(SYSTEM_MESSAGE_REMOTE_ID)
);

CREATE TABLE party (
  PARTY_ID varchar(40),
  PARTY_TYPE_ENUM_ID varchar(40),
  IS_ENABLED char(1),
  CREATED_DATE datetime(3),
  ENTRY_DATE datetime(3),
  LAST_MODIFIED_DATE datetime(3),
  OWNER_PARTY_ID varchar(40),
  EXTERNAL_ID varchar(40),
  PRIMARY KEY (PARTY_ID),
  FOREIGN KEY (OWNER_PARTY_ID) REFERENCES PARTY (PARTY_ID),
  FOREIGN KEY (PARTY_TYPE_ENUM_ID) REFERENCES ENUMERATION (ENUM_ID) 
);

CREATE TABLE role_type (
  ROLE_TYPE_ID varchar(40),
  PARENT_TYPE_ID varchar(40),
  DESCRIPTION varchar(40),
  LAST_UPDATED_STAMP datetime(3),
  PRIMARY KEY (ROLE_TYPE_ID)
);

CREATE TABLE contact_mech (
  CONTACT_MECH_ID varchar(40),
  CONTACT_MECH_TYPE_ENUM_ID varchar(40),
  INFO_STRING varchar(4095),
  LAST_UPDATED_STAMP datetime(3),
  PRIMARY KEY (CONTACT_MECH_ID)
);

CREATE TABLE contact_mech_purpose (
  CONTACT_MECH_PURPOSE_ID varchar(40),
  CONTACT_MECH_TYPE_ENUM_ID varchar(40),
  DESCRIPTION varchar(255),
  LAST_UPDATED_STAMP datetime(3),
  PRIMARY KEY (CONTACT_MECH_PURPOSE_ID),
  FOREIGN KEY (CONTACT_MECH_TYPE_ENUM_ID) REFERENCES enumeration(ENUM_ID)
);

CREATE TABLE person (
  PARTY_ID varchar(40),
  FIRST_NAME varchar(255),
  LAST_NAME varchar(255),
  DATE_OF_BIRTH date,
  LAST_UPDATED_STAMP datetime(3),
  PRIMARY KEY (PARTY_ID),
  FOREIGN KEY (PARTY_ID) REFERENCES party(PARTY_ID)
);

CREATE TABLE party_group (
  PARTY_ID varchar(40),
  GROUP_NAME varchar(63),
  LAST_UPDATED_STAMP datetime(3),
  PRIMARY KEY (PARTY_ID),
  FOREIGN KEY (PARTY_ID) REFERENCES party(PARTY_ID)
);

CREATE TABLE postal_address (
  CONTACT_MECH_ID varchar(40),
  TO_NAME varchar(4095),
  ADDRESS1 longtext,
  ADDRESS2 longtext,
  CITY varchar(255),
  POSTAL_CODE varchar(63),
  PROVINCE_GEO_ID varchar(40),
  COUNTRY_GEO_ID varchar(40),
  LAST_UPDATED_STAMP datetime(3),
  PRIMARY KEY (CONTACT_MECH_ID),
  FOREIGN KEY (CONTACT_MECH_ID) REFERENCES contact_mech(CONTACT_MECH_ID),
  FOREIGN KEY (PROVINCE_GEO_ID) REFERENCES geo(GEO_ID),
  FOREIGN KEY (COUNTRY_GEO_ID) REFERENCES geo(GEO_ID)
);

CREATE TABLE telecom_number (
  CONTACT_MECH_ID varchar(40),
  COUNTRY_CODE varchar(63),
  AREA_CODE varchar(63),
  CONTACT_NUMBER varchar(63),
  ASK_FOR_NAME varchar(255),
  LAST_UPDATED_STAMP datetime(3),
  PRIMARY KEY (CONTACT_MECH_ID),
  FOREIGN KEY (CONTACT_MECH_ID) REFERENCES contact_mech(CONTACT_MECH_ID)
);

CREATE TABLE party_attribute (
  PARTY_ID varchar(40),
  ATTR_NAME varchar(63),
  ATTR_VALUE varchar(255),
  ATTR_DESCRIPTION varchar(4095),
  LAST_UPDATED_STAMP datetime(3),
  PRIMARY KEY (PARTY_ID),
  FOREIGN KEY (PARTY_ID) REFERENCES party(PARTY_ID)
);

CREATE TABLE party_contact_mech (
  PARTY_ID varchar(40),
  CONTACT_MECH_ID varchar(40),
  CONTACT_MECH_PURPOSE_ID varchar(40),
  FROM_DATE datetime(3),
  THRU_DATE datetime(3),
  EXTENSION varchar(63),
  COMMENTS varchar(255),
  ALLOW_SOLICITATION char(1),
  LAST_UPDATED_STAMP datetime(3),
  PRIMARY KEY (PARTY_ID, CONTACT_MECH_ID, CONTACT_MECH_PURPOSE_ID, FROM_DATE),
  FOREIGN KEY (PARTY_ID) REFERENCES party(PARTY_ID),
  FOREIGN KEY (CONTACT_MECH_ID) REFERENCES contact_mech(CONTACT_MECH_ID),
  FOREIGN KEY (CONTACT_MECH_PURPOSE_ID) REFERENCES contact_mech_purpose(CONTACT_MECH_PURPOSE_ID)
);

CREATE TABLE party_role (
  PARTY_ID varchar(40),
  ROLE_TYPE_ID varchar(40),
  LAST_UPDATED_STAMP datetime(3),
  PRIMARY KEY (PARTY_ID, ROLE_TYPE_ID),
  FOREIGN KEY (PARTY_ID) REFERENCES party(PARTY_ID),
  FOREIGN KEY (ROLE_TYPE_ID) REFERENCES role_type(ROLE_TYPE_ID)
);

CREATE TABLE party_relationship (
  FROM_PARTY_ID varchar(40),
  FROM_ROLE_TYPE_ID varchar(40),
  TO_PARTY_ID varchar(40),
  TO_ROLE_TYPE_ID varchar(40),
  FROM_DATE datetime(3),
  PARTY_RELATIONSHIP_TYPE_ENUM_ID varchar(40),
  THRU_DATE datetime(3),
  STATUS_ID varchar(40),
  LAST_UPDATED_STAMP datetime(3),
  PRIMARY KEY (FROM_PARTY_ID, FROM_ROLE_TYPE_ID, TO_PARTY_ID, TO_ROLE_TYPE_ID, FROM_DATE),
  FOREIGN KEY (FROM_PARTY_ID) REFERENCES party(PARTY_ID),
  FOREIGN KEY (TO_PARTY_ID) REFERENCES party(PARTY_ID),
  FOREIGN KEY (FROM_ROLE_TYPE_ID) REFERENCES role_type(ROLE_TYPE_ID),
  FOREIGN KEY (TO_ROLE_TYPE_ID) REFERENCES role_type(ROLE_TYPE_ID)
);

CREATE TABLE tax_authority (
  TAX_AUTHORITY_ID varchar(40),
  TAX_AUTHORITY_TYPE_ENUM_ID varchar(40),
  DESCRIPTION varchar(255),
  TAX_AUTH_GEO_ID varchar(40),
  TAX_AUTH_PARTY_ID varchar(40),
  REQUIRE_TAX_ID_FOR_EXEMPTION char(1),
  TAX_ID_FORMAT_PATTERN varchar(255),
  INCLUDE_TAX_IN_PRICE char(1),
  PRIMARY KEY (TAX_AUTHORITY_ID),
  FOREIGN KEY (TAX_AUTHORITY_TYPE_ENUM_ID) REFERENCES enumeration(ENUM_ID),
  FOREIGN KEY (TAX_AUTH_GEO_ID) REFERENCES geo(GEO_ID),
  FOREIGN KEY (TAX_AUTH_PARTY_ID) REFERENCES party(PARTY_ID)
);

CREATE TABLE tax_authority_party (
  PARTY_ID varchar(40),
  TAX_AUTHORITY_ID varchar(40),
  FROM_DATE datetime(3),
  THRU_DATE datetime(3),
  PARTY_TAX_ID varchar(60),
  IS_EXEMPT char(1),
  IS_NEXUS char(1),
  PRIMARY KEY (PARTY_ID, TAX_AUTHORITY_ID, FROM_DATE),
  FOREIGN KEY (PARTY_ID) REFERENCES party(PARTY_ID),
  FOREIGN KEY (TAX_AUTHORITY_ID) REFERENCES tax_authority(TAX_AUTHORITY_ID)
);

CREATE TABLE party_identification (
  PARTY_ID varchar(40) NOT NULL,
  PARTY_IDENTIFICATION_TYPE_ENUM_ID varchar(40) NOT NULL,
  ID_VALUE varchar(255),
  ISSUED_BY varchar(255),
  ISSUED_BY_PARTY_ID varchar(40),
  EXPIRE_DATE date,
  PRIMARY KEY (PARTY_ID, PARTY_IDENTIFICATION_TYPE_ENUM_ID),
  FOREIGN KEY (PARTY_ID) REFERENCES party(PARTY_ID),
  FOREIGN KEY (PARTY_IDENTIFICATION_TYPE_ENUM_ID) REFERENCES enumeration(ENUM_ID),
  FOREIGN KEY (ISSUED_BY_PARTY_ID) REFERENCES party(PARTY_ID),
  INDEX IDX_PARTY_ID_VALUE (ID_VALUE)
);
